config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "posts#index"
  
  resources :posts do
    resources :comments
  end

  post "posts/:id", to: "comments#create", as: "create_comment"
  delete "comments/:id", to: "comments#destroy", as: "delete_comment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments , dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true, length: {minimum: 1, maximum: 50}
    validates :content, presence: true, length: {minimum: 5, maximum: 500}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, except: %i[create]

    def create
        # @post = Post.find(params[:post_id])
        # @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
        @comment = Comment.create(comment_params.merge(user_id: current_user.id))
        redirect_to post_path(:post_id)
    end

    def destroy
    if @user == true
        @comment.destroy

        respond_to do |format|
          format.html { redirect_to post_path(:post_id), notice: "Comment was successfully destroyed." }
          format.json { head :no_content }
        end
    else
        redirect_to post_path(:post_id), notice: "you can't delete that not yours!"
    end
    end


    private

    def set_comment
        @comment = Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:post_id, :content)
    end

    def check_user
        @user = false
        if(@comment.user.id == current_user.id)
          return @user = true
        else
          return @user
        end
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(:id)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @user == true
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to posts_url(@post)
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @user == true
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to posts_url(@post)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end

    def check_user
      @user = false
      if(@post.user.id == current_user.id)
        return @user = true
      else
        return @user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card mt-3">
<h2 class="card-header">comments</h2>
  <% @post.comments.each do |comment| %>
    <p>
      <strong>
        <%= comment.user.email%>
      </strong>
      <%= comment.content %>
        <%= button_to "Delete", delete_comment_url(comment), method: :delete %>
    </p>

  <% end %>

</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Whats Up!", root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%= link_to "Sign In", new_user_session_path , class: "nav-link" %>
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link" %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <main>
    <%= notice %>
    <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% #card untuk post %>
<div id="<%= dom_id post %>" class="card mx-auto mt-4" style="width: 50rem">
<% #Header post %>
    <div class="card-header">
        <h1><%= post.title %></h1>
    </div>
    <div class="card-body text-center">
        <%= post.content %>
    </div>
    <div class="card-footer">
        <p>
            <%= link_to "Show this post", post %>
        </p>   
    </div>     
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">

<h1>Posts</h1>
  <div id="posts">
    <% #ini looping untuk ruby post %>
    <% @posts.each do |post|%>
      <%= render post %>
    <% end %>
  </div>

  <%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= render @post %>

  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>

    <%= button_to "Delete Post", @post, method: :delete %>
  </div>

  <%= render 'comments/comment', post: @post %>

  <% #style comment %>

  <div class="card mt-3">
  <% if user_signed_in?%>

  <div class="container">
    <div class="row">
      <h2>Add a Comment</h2>
    </div>
    <div class="row">
      <%= form_with model: @comment, method: :post, url: create_comment_url do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>

      <div class="col">
        <%= form.text_field :user_id, type: :hidden, value: current_user.email %>
      </div>

    <div class="col">
      <%= form.text_area :content %>
    </div>
    <div class="col">
      <%= form.submit %>
    </div>
<% end %>
<% end %>
</div>
</div>

</div>